name: PR checks

on:
  pull_request:
  push:

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run ES Lint
        run: npm run lint

      - name: Type checking
        run: npx tsc --noEmit

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Create public directory if it doesn't exist
        run: mkdir -p public

      - name: Build Storybook
        run: npm run build-storybook -- --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta, blue" \
          "npx http-server storybook-static --port 6006 --silent" \
          "npx wait-on http://127.0.0.1:6006 && npm run test-storybook -- --coverage"
      
      - name: Run Vitest tests
        run: npm run test

      - name: Run tests with coverage
        run: npm run test:coverage